### ISSUE TITLE
How to run query on another database other than the default "test"?

### ISSUE THREAD

**Issue by john2x** [bitemyapp/revise#5]
Hi, sorry about posting an issue about a question, but I couldn't get a hold of you on `#clojure`.

In the README, it seems all operations are being done on the default database "test". How do I specify a different db? 

I tried 

```
(-> (q/db "my_db")
    (q/table "users")
    (q/get id))
```

but it seems it's still running against "test".

Thanks.

**Comment by cesarbp** [comment]
There are *-db functions which take the db as a first argument. Replace table for table-db

**Comment by john2x** [comment]
Ah thanks. Why the specific functions for the default db?

**Comment by cesarbp** [comment]
Some rethinkdb functions have optional arguments on different parts i saw no better way to implement that than making multiple functions.
