### ISSUE TITLE
Add Support for 1.11

### ISSUE THREAD

**Issue by cesarbp** [bitemyapp/revise#7]
accepts-json + the query changes

**Comment by cesarbp** [comment]
1.12 supported and tested. 6eaad45051800d25124812181f369cb68ca1a1a6

**Comment by ozanvos** [comment]
@cesarbp Any chance we could have a 0.1.0-SNAPSHOT release?

**Comment by cesarbp** [comment]
Yeah sure just need to fix an issue with the external protobuf libs.

**Comment by ozanvos** [comment]
@cesarbp great, looking forward to it!

**Comment by cesarbp** [comment]
Well the snapshot is up... I wanted to get the dependencies signed but I can't for the life of me figure out how to do it without breaking everything. I'll figure it out anyway before the actual release.

**Comment by ozanvos** [comment]
Works great with rethinkdb 1.12, thanks!
